### ISSUE TITLE
Code Contracts Editor Extensions 1.9.10714.2 crash when cut/parse unfinished code in VS2015

### ISSUE THREAD

**Issue by yyjdelete** [Microsoft/CodeContracts#248]
```
FDoIdle failed
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 ContractAdornments.TextViewTracker.OnNewComilation(Object compilationObject)
   在 ContractAdornments.VSServiceProvider.GetNewModel(ITextBuffer textBuffer)
   在 ContractAdornments.VSServiceProvider.<>c__DisplayClass17.<AskForNewVSModel>b__15()
   在 ContractAdornments.VSServiceProvider.FDoIdle(UInt32 grfidlef) 0:31.671
Code Contracts Editor Extensions 1.9.10714.2 14.0.23107.0 Visual Studio failed. 0:31.680
```

```
AugmentQuickInfoSession failed
System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: position
   在 Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia)
   在 Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.FindTokenCore(Int32 position, Boolean findInsideTrivia)
   在 ContractAdornments.IntellisenseContractsHelper.GetTargetAtTriggerPoint(ITrackingPoint triggerPoint, ITextSnapshot snapshot, SyntaxTree parseTree)
   在 ContractAdornments.QuickInfoSource.<>c__DisplayClass1.<AugmentQuickInfoSession>b__0()
   在 UtilitiesNamespace.Logger.PublicEntry(Action action, String entryName) 1:53.379
Code Contracts Editor Extensions 1.9.10714.2 14.0.23107.0 Visual Studio failed. 1:53.382
```

**Comment by roederja2** [comment]
I get the same crash.

**Comment by xperiandri** [comment]
I got crush on file open

**Comment by SergeyTeplyakov** [comment]
Thanks for sharing.
Up for grabs.

**Comment by piedar** [comment]
Same here.  I would like to fix it, but I haven't managed to get the project to build.

There aren't many things in `OnNewComilation(Object compilationObject)` that could be null.  I'm guessing that the [LatestCompilationChanged](https://github.com/Microsoft/CodeContracts/blob/b2021fb80abd1dbddd0ff5f2bb146ebe2acb5f9d/Microsoft.Research/ContractAdornments/CSharp/TextView/TextViewTracker.cs#L199) event handler becomes null between the check and invocation.

**Comment by SergeyTeplyakov** [comment]
Maybe @sharwell can shed some light regarding build issues. How are you trying to build it and what the error?

Regarding LatestCompilationChanged event: it can become null in multithreaded environment with race condition when the very last subscriber will unsubscribe right between the check and the invocation. That being said it means that it can happen only in very RARE cases, and if the problem is consistent that it's unrelated to this null check.

**Comment by piedar** [comment]
I managed to get the solution to build after switching from Debug to Devlab9 configuration.  How do I create the .vsix file so I can install/debug it in Visual Studio?

**Comment by fourpastmidnight** [comment]
My visual studio 2015 crashed 6 times tonight due to this extension. The last 4 times within the last 10 minutes!! I can't get anything done. Here's the exception info from the Code Contract Editor Extension tool window:

> AugmentQuickInfoSession failed
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: position
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.FindToken(Int32 position, Boolean findInsideTrivia)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.FindTokenCore(Int32 position, Boolean findInsideTrivia)
   at ContractAdornments.IntellisenseContractsHelper.GetTargetAtTriggerPoint(ITrackingPoint triggerPoint, ITextSnapshot snapshot, SyntaxTree parseTree)
   at ContractAdornments.QuickInfoSource.<>c__DisplayClass1.<AugmentQuickInfoSession>b__0()
   at UtilitiesNamespace.Logger.PublicEntry(Action action, String entryName) 0:58.646
Code Contracts Editor Extensions 1.9.10714.2 14.0.24720.0 Visual Studio failed. 0:58.646

**Comment by yaakov-h** [comment]
I installed it yesterday and it's crashed only a handful of times, but it's enough times to warrant an uninstall. Same stack trace.
