### ISSUE TITLE
NullReferenceException in Clousot/cccheck

### ISSUE THREAD

**Issue by HermanEldering** [Microsoft/CodeContracts#326]
Using 1.9.10714.2 in VS2015-U1. Unfortunately, I cannot share the code to reproduce this error.

    Internal error in Clousot/cccheck --- catching it, and continuing
    \nException Type:System.NullReferenceException
    \nMessage:Object reference not set to an instance of an object.\, Stack TraceSystem.NullReferenceException: Object reference not set to an instance of an object.
    \n at System.Compiler.Analysis.CCIMDDecoder.IsStruct(TypeNode type)
    \n at Microsoft.Research.CodeAnalysis.Extensions.HasValueRepresentation[Local\, Parameter\, Method\, Field\, Property\, Event\, Type\, Attribute\, Assembly](IDecodeMetaData`9 mdDecoder\, Type type)
    \n at Microsoft.Research.CodeAnalysis.OptimisticHeapAnalyzer`9.Domain.IsStructWithFields(FlatDomain`1 valueType)
    \n at Microsoft.Research.CodeAnalysis.OptimisticHeapAnalyzer`9.Domain.CopyOld(Int32 dest\, Int32 source\, Type type)
    \n at Microsoft.Research.CodeAnalysis.OptimisticHeapAnalyzer`9.Domain.AnalysisDecoder.EndOld(APC pc\, APC matchingBegin\, Type type\, Int32 dest\, Int32 source\, Domain data)
    \n at Microsoft.Research.CodeAnalysis.StackDepthProvider`10.StackDecoder`3.EndOld(APC pc\, APC matchingBegin\, Type type\, Unit dest\, Unit source\, Data data)
    \n at Microsoft.Research.CodeAnalysis.APCDecoder`9.RemoveBranchDelegator`3.EndOld(APC pc\, APC matchingBegin\, Type type\, Unit dest\, Unit source\, Data data)
    \n at Microsoft.Research.CodeAnalysis.MethodCache`9.BlockWithLabels`1.LabelAdapter`3.EndOld(Label pc\, Label matchingBegin\, Type type\, Unit dest\, Unit source\, Data data)
    \n at System.Compiler.Analysis.CCIILProvider.Decode[Visitor\, Data\, Result](PC pc\, Visitor visit\, Data data)
    \n at Microsoft.Research.CodeAnalysis.MethodCache`9.BlockWithLabels`1.ForwardDecode[Data\, Result\, Visitor](APC pc\, Visitor visitor\, Data data)
    \n at Microsoft.Research.CodeAnalysis.MethodCache`9.ForwardDecode[Data\, Result\, Visitor](APC pc\, Visitor visitor\, Data data)
    \n at Microsoft.Research.CodeAnalysis.APCDecoder`9.ForwardDecode[Data\, Result\, Visitor](APC pc\, Visitor visitor\, Data data)
    \n at Microsoft.Research.CodeAnalysis.StackDepthProvider`10.ForwardDecode[Data\, Result\, Visitor](APC lab\, Visitor visitor\, Data data)
    \n at Microsoft.Research.CodeAnalysis.ForwardAnalysisSolver`3.<>c__DisplayClass3`7.<Make>b__0(APC pc\, AState state)
    \n at Microsoft.Research.CodeAnalysis.ForwardAnalysisSolver`3.Transfer(APC pc\, AState state)
    \n at Microsoft.Research.CodeAnalysis.DFARoot`2.ComputeFixpoint()
    \n at Microsoft.Research.CodeAnalysis.ForwardDFA`2.Run(AState startState)
    \n at Microsoft.Research.CodeAnalysis.CodeLayer`13.<>c__DisplayClass1`1.<CreateForward>b__0(AnalysisState initialState)
    \n at Microsoft.Research.CodeAnalysis.OldAnalysisDriver`11.MDriver.RunHeapAndExpressionAnalyses()
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.MethodAnalysisNonCached(Method method\, MethodAnalysisFlags& analysisFlags\, Int32& phasecount\, String methodFullName\, IClassDriver`13 cdriver\, IMethodDriver`12 mdriver\, AnalysisStatistics& methodStats\, ContractDensity& methodContractDensity)
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeMethodInternal2(Method method\, MethodAnalysisFlags analysisFlags\, IClassDriver`13& cdriver\, AnalysisStatistics& methodStats\, APC& entryPC)

**Comment by SergeyTeplyakov** [comment]
Any chances to nail error down to some small sample?
