### ISSUE TITLE
ArgumentNullException in ccchecker

### ISSUE THREAD

**Issue by HermanEldering** [Microsoft/CodeContracts#327]
Using 1.9.10714.2 in VS2015-U1. Unfortunately, I cannot share the code to reproduce this error. With cache enabled I get the exception below, when I disable the cache the exception goes away.

    Internal error at method Method 188 :  <removed>
    Failed with uncaught exception: Value cannot be null.
    \nParameter name: key
    Stack trace:    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
    \n at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key\, TValue& value)
    \n at Microsoft.Research.CodeAnalysis.CacheManager`11.GetOrCreateReferencedTypeLocalId(Type typ)
    \n at Microsoft.Research.CodeAnalysis.MethodHasher`12.ILHasher.EndOld(APC pc\, APC matchingBegin\, Type type\, Int32 dest\, Int32 source\, Unit data)
    \n at Microsoft.Research.CodeAnalysis.StackDepthProvider`10.StackDecoder`3.EndOld(APC pc\, APC matchingBegin\, Type type\, Unit dest\, Unit source\, Data data)
    \n at Microsoft.Research.CodeAnalysis.APCDecoder`9.RemoveBranchDelegator`3.EndOld(APC pc\, APC matchingBegin\, Type type\, Unit dest\, Unit source\, Data data)
    \n at Microsoft.Research.CodeAnalysis.MethodCache`9.BlockWithLabels`1.LabelAdapter`3.EndOld(Label pc\, Label matchingBegin\, Type type\, Unit dest\, Unit source\, Data data)
    \n at System.Compiler.Analysis.CCIILProvider.Decode[Visitor\, Data\, Result](PC pc\, Visitor visit\, Data data)
    \n at Microsoft.Research.CodeAnalysis.MethodCache`9.BlockWithLabels`1.ForwardDecode[Data\, Result\, Visitor](APC pc\, Visitor visitor\, Data data)
    \n at Microsoft.Research.CodeAnalysis.MethodCache`9.ForwardDecode[Data\, Result\, Visitor](APC pc\, Visitor visitor\, Data data)
    \n at Microsoft.Research.CodeAnalysis.APCDecoder`9.ForwardDecode[Data\, Result\, Visitor](APC pc\, Visitor visitor\, Data data)
    \n at Microsoft.Research.CodeAnalysis.StackDepthProvider`10.ForwardDecode[Data\, Result\, Visitor](APC lab\, Visitor visitor\, Data data)
    \n at Microsoft.Research.CodeAnalysis.MethodHasher`12.HashSubroutine(Subroutine subroutine)
    \n at Microsoft.Research.CodeAnalysis.MethodHasher`12.HashSubroutine(Subroutine subroutine)
    \n at Microsoft.Research.CodeAnalysis.MethodHasher`12.HashSubroutine(Subroutine subroutine)
    \n at Microsoft.Research.CodeAnalysis.MethodHasher`12.GetHash(Byte[] AdditionalOptionsToHash)
    \n at Microsoft.Research.CodeAnalysis.CacheManager`11.ComputeMethodHash(IMethodDriver`12 mDriver\, Boolean trace)
    \n at Microsoft.Research.CodeAnalysis.CacheManager`11.StartMethod(IMethodDriver`12 mDriver\, IClassDriver`13 cDriver\, FieldsDB`9 fieldsDB\, Boolean trace)
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeMethodInternal2(Method method\, MethodAnalysisFlags analysisFlags\, IClassDriver`13& cdriver\, AnalysisStatistics& methodStats\, APC& entryPC)
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeMethodInternal(Method method\, MethodAnalysisFlags analysisFlags)
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeMethod(Method method)
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.DoWork(Int32 totalMethods\, Int32& progressChars\, Stopwatch assemblyStopWatch\, Method method)
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeMethodsInAssembly(Int32 totalMethods\, Int32 progressChars\, Stopwatch stopWatch)
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeAssemblyInternal(Int32 totalMethods\, Int32 progressChars\, Stopwatch stopWatch)
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeAssembly(Assembly assembly\, Set`1 assembliesUnderAnalysis)
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.InternalAnalyze()
    \n at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.Analyze()

**Comment by SergeyTeplyakov** [comment]
Is it possible to reproduce the issue with small fake solution?
